version: '3.1'

services:
  db: 
    image: postgres
    container_name: ${DB_NAME}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:${DB_PORT}