version: '3.1'

services:
  db: 
    image: postgres
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: todo_db
    ports:
      - 5432:5432